# The main job for flights_project
resources:
  jobs:
    flights_notebook:
      name: flights_advanced_notebook_job_${bundle.target}
      max_concurrent_runs: 1
      
      parameters:
        - name: catalog
          default: main
        - name: database
          default: flights_dev

      tasks:
        - task_key: notebook_task
          notebook_task:
            notebook_path: ../src/flights_main_notebook.py
            base_parameters:
                artifact_path: ${workspace.artifact_path}
          max_retries: 0

